version: "3.4"

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
      - "5400:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
      - "5401:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb; Port=5432; Database=CatalogDb; User Id=postgres; Password=postgres; Include Error Detail=true

      - Kestrel__Endpoints__Http__Url=http://*:8080
      - Kestrel__Endpoints__Https__Url=https://*:8081
      - Kestrel__Endpoints__Https__Certificate__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - Kestrel__Endpoints__Https__Certificate__Password=david
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb; Port=5432; Database=BasketDb; User Id=postgres; Password=postgres; Include Error Detail=true
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081

      - Kestrel__Endpoints__Http__Url=http://*:8080
      - Kestrel__Endpoints__Https__Url=https://*:8081
      - Kestrel__Endpoints__Https__Certificate__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - Kestrel__Endpoints__Https__Certificate__Password=david
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb.db

      - Kestrel__Endpoints__Http__Url=http://*:8080
      - Kestrel__Endpoints__Https__Url=https://*:8081
      - Kestrel__Endpoints__Https__Certificate__Path=/home/app/.aspnet/https/aspnetapp.pfx
      - Kestrel__Endpoints__Https__Certificate__Password=david
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets:ro
      - ${HOME}/.aspnet/https:/home/app/.aspnet/https:ro
      # - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
